# pakage import

In [2]:
import numpy as np

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

from torchvision import datasets, transforms

import matplotlib.pyplot as plt

## Torch tensor란

In [7]:
a = torch.tensor([[1.0, 4.0], [4.0, 3.0]], device=0)
b = torch.tensor([[4, 3], [1, 4], [1, 2]], dtype=torch.int64, device='cpu')
print(a)
print(b)

tensor([[1., 4.],
        [4., 3.]], device='cuda:0')
tensor([[4, 3],
        [1, 4],
        [1, 2]])


In [8]:
print(a.dtype, a.device, a.shape)
print(b.dtype, b.device, b.shape)

torch.float32 cuda:0 torch.Size([2, 2])
torch.int64 cpu torch.Size([3, 2])


In [5]:
a = torch.Tensor([[4, 2], [2, 1]])
print(a.dtype, a.device)

torch.float32 cpu


In [6]:
a = torch.ones([2, 3])
b = torch.zeros([3, 2], dtype=torch.int64)
c = torch.eye(4)
d = torch.rand([2, 4, 3])  

In [7]:
print(a)
print(b)
print(c)
print(d)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0, 0],
        [0, 0],
        [0, 0]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[[0.3145, 0.9455, 0.1947],
         [0.2652, 0.3791, 0.3721],
         [0.4361, 0.7967, 0.0696],
         [0.9716, 0.0476, 0.8572]],

        [[0.1304, 0.8133, 0.0749],
         [0.7270, 0.6376, 0.0318],
         [0.9444, 0.3746, 0.0669],
         [0.1307, 0.2664, 0.9708]]])


In [8]:
d = np.array([[2, 5, 4], [4, 2, 1], [5, 7, 4]])
a = torch.tensor(d)
b = torch.from_numpy(d)

print(a)
print(b)
print(d)

tensor([[2, 5, 4],
        [4, 2, 1],
        [5, 7, 4]])
tensor([[2, 5, 4],
        [4, 2, 1],
        [5, 7, 4]])
[[2 5 4]
 [4 2 1]
 [5 7 4]]


In [10]:
 d[0, 0] = 100
 print(a)
 print(b)

tensor([[2, 5, 4],
        [4, 2, 1],
        [5, 7, 4]])
tensor([[100,   5,   4],
        [  4,   2,   1],
        [  5,   7,   4]])


In [11]:
b = torch.ones_like(a)
c = torch.zeros_like(a, dtype=torch.float)
d = torch.rand_like(a, dtype=torch.float)

print(b)
print(c)
print(d)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5743, 0.4334, 0.2920],
        [0.9646, 0.5094, 0.7291],
        [0.8593, 0.6486, 0.2571]])


In [3]:
torch.cuda.is_available()

True

In [5]:
if torch.cuda.is_available():
  a = torch.tensor([[4, 3, 2], [1, 2, 3]])
  print(a)
  b = a.to('cuda')
  print(b)

tensor([[4, 3, 2],
        [1, 2, 3]])
tensor([[4, 3, 2],
        [1, 2, 3]], device='cuda:0')


In [6]:
b[0][0] = 100
print(a)
print(b)

tensor([[4, 3, 2],
        [1, 2, 3]])
tensor([[100,   3,   2],
        [  1,   2,   3]], device='cuda:0')


In [20]:
a = torch.rand([2, 3])
b = torch.rand([2, 3])
print(a)
print(b)

tensor([[0.3062, 0.5970, 0.3831],
        [0.1304, 0.5641, 0.2215]])
tensor([[0.6166, 0.0990, 0.0286],
        [0.8445, 0.9684, 0.7971]])


In [21]:
c = torch.cat([a, b], dim=0)
d = torch.cat([a, b], dim=1)
print(c)
print(c.shape)
print(d)
print(d.shape)

tensor([[0.3062, 0.5970, 0.3831],
        [0.1304, 0.5641, 0.2215],
        [0.6166, 0.0990, 0.0286],
        [0.8445, 0.9684, 0.7971]])
torch.Size([4, 3])
tensor([[0.3062, 0.5970, 0.3831, 0.6166, 0.0990, 0.0286],
        [0.1304, 0.5641, 0.2215, 0.8445, 0.9684, 0.7971]])
torch.Size([2, 6])


In [22]:
c = torch.stack([a, b], dim=0)
d = torch.stack([a, b], dim=1)
e = torch.stack([a, b], dim=2)
print(c)
print(c.shape)
print(d)
print(d.shape)
print(e)
print(e.shape)

tensor([[[0.3062, 0.5970, 0.3831],
         [0.1304, 0.5641, 0.2215]],

        [[0.6166, 0.0990, 0.0286],
         [0.8445, 0.9684, 0.7971]]])
torch.Size([2, 2, 3])
tensor([[[0.3062, 0.5970, 0.3831],
         [0.6166, 0.0990, 0.0286]],

        [[0.1304, 0.5641, 0.2215],
         [0.8445, 0.9684, 0.7971]]])
torch.Size([2, 2, 3])
tensor([[[0.3062, 0.6166],
         [0.5970, 0.0990],
         [0.3831, 0.0286]],

        [[0.1304, 0.8445],
         [0.5641, 0.9684],
         [0.2215, 0.7971]]])
torch.Size([2, 3, 2])


In [23]:
c = torch.hstack([a, b])
print(c)
print(c.shape)
d = torch.vstack([a, b])
print(d)
print(d.shape)

tensor([[0.3062, 0.5970, 0.3831, 0.6166, 0.0990, 0.0286],
        [0.1304, 0.5641, 0.2215, 0.8445, 0.9684, 0.7971]])
torch.Size([2, 6])
tensor([[0.3062, 0.5970, 0.3831],
        [0.1304, 0.5641, 0.2215],
        [0.6166, 0.0990, 0.0286],
        [0.8445, 0.9684, 0.7971]])
torch.Size([4, 3])


In [24]:
print(a)
a = torch.unsqueeze(a, dim=1)
print(a)
print(a.shape)

a = torch.squeeze(a)
print(a)
print(a.shape)

tensor([[0.3062, 0.5970, 0.3831],
        [0.1304, 0.5641, 0.2215]])
tensor([[[0.3062, 0.5970, 0.3831]],

        [[0.1304, 0.5641, 0.2215]]])
torch.Size([2, 1, 3])
tensor([[0.3062, 0.5970, 0.3831],
        [0.1304, 0.5641, 0.2215]])
torch.Size([2, 3])


In [25]:
a = torch.tensor(np.array(list(range(12)))).reshape(3, 4)
b = torch.tensor(np.array(list(range(8)))).reshape(4, 2)
print(np.array(list(range(12))))
print(torch.tensor(np.array(list(range(12)))))
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])


In [26]:
c = a @ b
print(c)

tensor([[ 28,  34],
        [ 76,  98],
        [124, 162]])


In [27]:
d = torch.matmul(a, b)
print(d)

tensor([[ 28,  34],
        [ 76,  98],
        [124, 162]])


In [28]:
torch.matmul(a, b, out=e)
print(e)

RuntimeError: ignored

In [29]:
a = torch.tensor(np.array(list(range(6)))).reshape(2, 3)
b = torch.tensor(np.array(list(range(10, 16)))).reshape(2, 3)
print(a)
print(b)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[10, 11, 12],
        [13, 14, 15]])


In [30]:
c = a * b
print(c)

tensor([[ 0, 11, 24],
        [39, 56, 75]])


In [31]:
d = torch.mul(a, b)
print(d)

tensor([[ 0, 11, 24],
        [39, 56, 75]])


In [32]:
agg = d.sum()
v = agg.item()
print(v, type(v))

205 <class 'int'>


In [33]:
print(a)
a.add_(5)
print(a)
a.add_(b)
print(a)

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[ 5,  6,  7],
        [ 8,  9, 10]])
tensor([[15, 17, 19],
        [21, 23, 25]])


In [34]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [35]:
a.add_(5)
print(a)
print(b)

tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]
